### ISSUE TITLE
[Bug|] Docker setup fails on windows?

### ISSUE THREAD

**Issue by GeofoxCoding** [laramies/theHarvester#1048]
Bug

**Describe the feature request or bug or other**
Hello,

I wanted to try theHarvester from my Windows 11 notebook with Docker Desktop for a small security assessment

**To Reproduce**
I followed your simple docker setup and the image builds fine but once I try to start a container I get
$ docker run theharvester -h
/usr/bin/env: 'python3\r': No such file or directory

I tried to replace line endings in the Dockerfile itself but this may not be the problem because it build correctly. So where could this error come from.

**Expected behaviour**
The harvester container should start correctly with python 3 and harvester service running.

**Screenshots**
-
**System Information (System that tool is running on):**
 - OS: Windows 11 Pro 21H2
 - Version latest

Thank you for your help. It would be great if I could use the tool :).

**Comment by L1ghtn1ng** [comment]
Does it work if you remove env from theHarvester.py file?


On 10 Mar 2022, at 16:18, GeofoxCoding ***@***.***> wrote:

﻿

Bug

Describe the feature request or bug or other
Hello,

I wanted to try theHarvester from my Windows 11 notebook with Docker Desktop for a small security assessment

To Reproduce
I followed your simple docker setup and the image builds fine but once I try to start a container I get
$ docker run theharvester -h
/usr/bin/env: 'python3\r': No such file or directory

I tried to replace line endings in the Dockerfile itself but this may not be the problem because it build correctly. So where could this error come from.

Expected behaviour
The harvester container should start correctly with python 3 and harvester service running.

Screenshots

System Information (System that tool is running on):

  *   OS: Windows 11 Pro 21H2
  *   Version latest

Thank you for your help. It would be great if I could use the tool :).

**Comment by GeofoxCoding** [comment]
After I changed `#!/usr/bin/env` into `#!/usr/bin` inside theHarvester.py AND restfulHarvest.py the error disappears and now I get a new error:

$ docker run theharvester -h
standard_init_linux.go:228: exec user process caused: permission denied

**Comment by L1ghtn1ng** [comment]
@NotoriousRebel can you comment on this please?

**Comment by NotoriousRebel** [comment]
Hi @GeofoxCoding maybe this [post](https://stackoverflow.com/questions/59767901/standard-init-linux-go211-exec-user-process-caused-permission-denied) would be helpful. Try following the advice there and see if that works.

**Comment by L1ghtn1ng** [comment]
Timeout
