### ISSUE TITLE
still having isses on theHarvester on my kali saying google is blocking my ip

### ISSUE THREAD

**Issue by Bigzeek01** [laramies/theHarvester#1103]
pls has anybody been able to fix the google is blocking my ip error when using theHarvester?

**Comment by runningwithcoffee** [comment]
im also having the same problem, getting no output afterwards?

**Comment by L1ghtn1ng** [comment]
Unfortunately there is nothing that can be done, in the next realise that I push to the repo anything that requires the use of Google has been removed as it just does not work due to Google blocking it

On 23 May 2022, at 10:02, Emir ***@***.***> wrote:

﻿

im also having the same problem, getting no output afterwards?

**Comment by L1ghtn1ng** [comment]
This has been resolved in my branch by removing modules that use google as there is no way really around this issue for now at least
