### ISSUE TITLE
Cannot Run on Kali Linux 2021.3 ARM64

### ISSUE THREAD

**Issue by tim5700** [laramies/theHarvester#1183]
Does not run on Kali

**Describe the feature request or bug or other**
Trying to run theHarvester from Kali Linux.  Run the following: theHarvester -h

I get the following:
[!] Make sure you have Python 3.7+ installed, quitting.

**To Reproduce**
Steps to reproduce the behaviour:
1. Run "theHarvester"

**Expected behaviour**
Be able to run theHarvester.

**Screenshots**
<img width="488" alt="Screen Shot 2022-08-14 at 4 54 56 PM" src="https://user-images.githubusercontent.com/16280018/184554655-d31e97b3-268c-4f5c-87b0-b5e431de9c45.png">

**System Information (System that tool is running on):**
- OS Kali 2021.3 ARM64
- VM running in Parallels 18.0.0
- MacBook Pro 16-inch 2021 M1 Pro, MacOS 12.5

**Additional context**

**Comment by L1ghtn1ng** [comment]
Can you redo the VM with the latest kali image and see if you get the issue still?

On 14 Aug 2022, at 22:00, tim5700 ***@***.***> wrote:

﻿

Does not run on Kali

Describe the feature request or bug or other
Trying to run theHarvester from Kali Linux. Run the following: theHarvester -h

I get the following:
[!] Make sure you have Python 3.7+ installed, quitting.

To Reproduce
Steps to reproduce the behaviour:

  1.  Run "theHarvester"

Expected behaviour
Be able to run theHarvester.

Screenshots
[Screen Shot 2022-08-14 at 4 54 56 PM]<https://user-images.githubusercontent.com/16280018/184554655-d31e97b3-268c-4f5c-87b0-b5e431de9c45.png>

System Information (System that tool is running on):

  *   OS Kali 2021.3 ARM64
  *   VM running in Parallels 18.0.0
  *   MacBook Pro 16-inch 2021 M1 Pro, MacOS 12.5

Additional context
Add any other context about the problem here.

**Comment by L1ghtn1ng** [comment]
Also from the screenshot you are using the the one that is installed system wide but looks like you have cloned theHarvester from git as you are in the theHarvester directory which you will need to run it like the following ./theHarvester.py

On 14 Aug 2022, at 22:00, tim5700 ***@***.***> wrote:

﻿

Does not run on Kali

Describe the feature request or bug or other
Trying to run theHarvester from Kali Linux. Run the following: theHarvester -h

I get the following:
[!] Make sure you have Python 3.7+ installed, quitting.

To Reproduce
Steps to reproduce the behaviour:

  1.  Run "theHarvester"

Expected behaviour
Be able to run theHarvester.

Screenshots
[Screen Shot 2022-08-14 at 4 54 56 PM]<https://user-images.githubusercontent.com/16280018/184554655-d31e97b3-268c-4f5c-87b0-b5e431de9c45.png>

System Information (System that tool is running on):

  *   OS Kali 2021.3 ARM64
  *   VM running in Parallels 18.0.0
  *   MacBook Pro 16-inch 2021 M1 Pro, MacOS 12.5

Additional context
Add any other context about the problem here.

**Comment by tim5700** [comment]
That appears to have worked.  Thanks.

On Aug 14, 2022, at 5:17 PM, J.Townsend ***@***.******@***.***>> wrote:


Also from the screenshot you are using the the one that is installed system wide but looks like you have cloned theHarvester from git as you are in the theHarvester directory which you will need to run it like the following ./theHarvester.py

On 14 Aug 2022, at 22:00, tim5700 ***@***.***> wrote:

﻿

Does not run on Kali

Describe the feature request or bug or other
Trying to run theHarvester from Kali Linux. Run the following: theHarvester -h

I get the following:
[!] Make sure you have Python 3.7+ installed, quitting.

To Reproduce
Steps to reproduce the behaviour:

1. Run "theHarvester"

Expected behaviour
Be able to run theHarvester.

Screenshots
[Screen Shot 2022-08-14 at 4 54 56 PM]<https://user-images.githubusercontent.com/16280018/184554655-d31e97b3-268c-4f5c-87b0-b5e431de9c45.png>

System Information (System that tool is running on):

* OS Kali 2021.3 ARM64
* VM running in Parallels 18.0.0
* MacBook Pro 16-inch 2021 M1 Pro, MacOS 12.5

Additional context
Add any other context about the problem here.
