### ISSUE TITLE
Invalid Source - Ubuntu 22.04

### ISSUE THREAD

**Issue by fpapso** [laramies/theHarvester#1202]
Hi - I get an error when I try to run theHarvester on a Ubuntu 22.04 

Error: invalid source 

I run the same command on my kali : theHarvester -d kali.org -b google. 

I have install the pip3 install -r requirements.txt

Directory / /home/tools/theHarvester 

Any suggestion?

**Comment by L1ghtn1ng** [comment]
That is due to Google having been removed as it kept getting blocked by Google

On 7 Sep 2022, at 13:05, DDL_devlop ***@***.***> wrote:

﻿

Hi - I get an error when I try to run theHarvester on a Ubuntu 22.04

Error: invalid source

I run the same command on my kali : theHarvester -d kali.org -b google.

I have install the pip3 install -r requirements.txt

Directory / /home/tools/theHarvester

Any suggestion?
