### ISSUE TITLE
ModuleNotFoundError: No module named 'theHarvester'

### ISSUE THREAD

**Issue by JumboJetFighter** [laramies/theHarvester#1222]
Traceback (most recent call last):
  File "main.py", line 5, in <module>
    from theHarvester import __main__
ModuleNotFoundError: No module named 'theHarvester'

**Comment by L1ghtn1ng** [comment]
What version of theHarvester you using and what operating system and how did you install it?

**Comment by L1ghtn1ng** [comment]
Timeout

**Comment by ollay2023** [comment]
Hello everyone, i stumbled on this site https://tech.lobobrothers.com/theharvester-christian-martorella where i saw how to resolve issues with theHarvester installation. These are the instruction in word file as follows

[HARVESTING.docx](https://github.com/laramies/theHarvester/files/13555408/HARVESTING.docx)

After everything has been done, i still get the following error 

Traceback (most recent call last):
File "/opt/theHarvester-master/theHarvester.py" , line 5, in <module> 
 from theHarvester.theHarvester import main
File "/opt/theHarvester-master/theHarvester/theHarvester.py" , line 4, in <module>
     from theHarvester import __main__
File "/opt/theHarvester-master/theHarvester/__main__ .py", line 12 in <module>
     import netaddr
ModuleNotFoundError : No module named 'netaddr'

Please any help on this issue?

**Comment by L1ghtn1ng** [comment]
If you use pipx to install that will solve your issues no problem due to recent updates in git ☺️

On 5 Dec 2023, at 05:11, ollay2023 ***@***.***> wrote:

﻿

Hello everyone, i stumbled on this site https://tech.lobobrothers.com/theharvester-christian-martorella where i saw how to resolve issues with theHarvester installation. These are the instruction in word file as follows

HARVESTING.docx<https://github.com/laramies/theHarvester/files/13555408/HARVESTING.docx>

After everything has been done, i still get the following error

Traceback (most recent call last):
File "/opt/theHarvester-master/theHarvester.py" , line 5, in
from theHarvester.theHarvester import main
File "/opt/theHarvester-master/theHarvester/theHarvester.py" , line 4, in
from theHarvester import main
File "/opt/theHarvester-master/theHarvester/main .py", line 12 in
import netaddr
ModuleNotFoundError : No module named 'netaddr'

Please any help on this issue?
