### ISSUE TITLE
Getting error when launching theHarvester in ParrotOS

### ISSUE THREAD

**Issue by RicardoMarin9303** [laramies/theHarvester#1234]
Traceback (most recent call last):
  File "/home/yolirica/Descargas/theHarvester/theHarvester.py", line 5, in <module>
    from theHarvester import __main__
  File "/home/yolirica/Descargas/theHarvester/theHarvester/__main__.py", line 4, in <module>
    from theHarvester.discovery import dnssearch, takeover, shodansearch
  File "/home/yolirica/Descargas/theHarvester/theHarvester/discovery/dnssearch.py", line 14, in <module>
    from aiodns import DNSResolver
ModuleNotFoundError: No module named 'aiodns'

**Comment by L1ghtn1ng** [comment]
Is this from the parrot os packages for theHarvester or installing it from git?

On 24 Oct 2022, at 14:12, RicardoMarin9303 ***@***.***> wrote:

﻿

Traceback (most recent call last):
File "/home/yolirica/Descargas/theHarvester/theHarvester.py", line 5, in
from theHarvester import main
File "/home/yolirica/Descargas/theHarvester/theHarvester/main.py", line 4, in
from theHarvester.discovery import dnssearch, takeover, shodansearch
File "/home/yolirica/Descargas/theHarvester/theHarvester/discovery/dnssearch.py", line 14, in
from aiodns import DNSResolver
ModuleNotFoundError: No module named 'aiodns'

**Comment by RicardoMarin9303** [comment]
> Is this from the parrot os packages for theHarvester or installing it from git?

I downloaded theHarvester from the github repositories, when I tried to run the program with the command:

`python3.10 theHarvester.py -h`

The following error appears in the terminal:

```
Traceback (most recent call last):
  File "/home/yolirica/Descargas/theHarvester/theHarvester.py", line 5, in <module>
    from theHarvester import __main__
  File "/home/yolirica/Descargas/theHarvester/theHarvester/__main__.py", line 4, in <module>
    from theHarvester.discovery import dnssearch, takeover, shodansearch
  File "/home/yolirica/Descargas/theHarvester/theHarvester/discovery/dnssearch.py", line 14, in <module>
    from aiodns import DNSResolver
ModuleNotFoundError: No module named 'aiodns
```
I have already installed Python in its version 3.10, I have tried to use other versions of Python and I still have the same problem.

When I try to install the requirements with the following command 
`python3 -m pip install -r base.txt` 

the following error appears:
``` 
Defaulting to user installation because normal site-packages is not writeable
WARNING: pip is configured with locations that require TLS/SSL, however the ssl module in Python is not available.
ERROR: Could not open requirements file: [Errno 2] No existe el fichero o el directorio: 'base.txt'
WARNING: pip is configured with locations that require TLS/SSL, however the ssl module in Python is not available.
Could not fetch URL https://pypi.org/simple/pip/: There was a problem confirming the ssl certificate: HTTPSConnectionPool(host='pypi.org', port=443): Max retries exceeded with url: /simple/pip/ (Caused by SSLError("Can't connect to HTTPS URL because the SSL module is not available.")) - skipping
WARNING: There was an error checking the latest version of pip. 
```

**Comment by L1ghtn1ng** [comment]
Please read the wiki page and have a look at the installation guide, that will sort you right out

On 24 Oct 2022, at 14:42, RicardoMarin9303 ***@***.***> wrote:

﻿

Is this from the parrot os packages for theHarvester or installing it from git?

I downloaded theHarvester from the github repositories, when I tried to run the program with the command:

python3.10 theHarvester.py -h

The following error appears in the terminal:

Traceback (most recent call last):
  File "/home/yolirica/Descargas/theHarvester/theHarvester.py", line 5, in <module>
    from theHarvester import __main__
  File "/home/yolirica/Descargas/theHarvester/theHarvester/__main__.py", line 4, in <module>
    from theHarvester.discovery import dnssearch, takeover, shodansearch
  File "/home/yolirica/Descargas/theHarvester/theHarvester/discovery/dnssearch.py", line 14, in <module>
    from aiodns import DNSResolver
ModuleNotFoundError: No module named 'aiodns


I have already installed Python in its version 3.10, I have tried to use other versions of Python and I still have the same problem.

When I try to install the requirements with the following command
python3 -m pip install -r base.txt

the following error appears:

Defaulting to user installation because normal site-packages is not writeable
WARNING: pip is configured with locations that require TLS/SSL, however the ssl module in Python is not available.
ERROR: Could not open requirements file: [Errno 2] No existe el fichero o el directorio: 'base.txt'
WARNING: pip is configured with locations that require TLS/SSL, however the ssl module in Python is not available.
Could not fetch URL https://pypi.org/simple/pip/: There was a problem confirming the ssl certificate: HTTPSConnectionPool(host='pypi.org', port=443): Max retries exceeded with url: /simple/pip/ (Caused by SSLError("Can't connect to HTTPS URL because the SSL module is not available.")) - skipping
WARNING: There was an error checking the latest version of pip.

**Comment by L1ghtn1ng** [comment]
On the GitHub repo in your browser there is a wiki tab, click on that and you will be good 😊

On 24 Oct 2022, at 14:46, Jay Townsend ***@***.***> wrote:

﻿ Please read the wiki page and have a look at the installation guide, that will sort you right out

On 24 Oct 2022, at 14:42, RicardoMarin9303 ***@***.***> wrote:

﻿

Is this from the parrot os packages for theHarvester or installing it from git?

I downloaded theHarvester from the github repositories, when I tried to run the program with the command:

python3.10 theHarvester.py -h

The following error appears in the terminal:

Traceback (most recent call last):
  File "/home/yolirica/Descargas/theHarvester/theHarvester.py", line 5, in <module>
    from theHarvester import __main__
  File "/home/yolirica/Descargas/theHarvester/theHarvester/__main__.py", line 4, in <module>
    from theHarvester.discovery import dnssearch, takeover, shodansearch
  File "/home/yolirica/Descargas/theHarvester/theHarvester/discovery/dnssearch.py", line 14, in <module>
    from aiodns import DNSResolver
ModuleNotFoundError: No module named 'aiodns


I have already installed Python in its version 3.10, I have tried to use other versions of Python and I still have the same problem.

When I try to install the requirements with the following command
python3 -m pip install -r base.txt

the following error appears:

Defaulting to user installation because normal site-packages is not writeable
WARNING: pip is configured with locations that require TLS/SSL, however the ssl module in Python is not available.
ERROR: Could not open requirements file: [Errno 2] No existe el fichero o el directorio: 'base.txt'
WARNING: pip is configured with locations that require TLS/SSL, however the ssl module in Python is not available.
Could not fetch URL https://pypi.org/simple/pip/: There was a problem confirming the ssl certificate: HTTPSConnectionPool(host='pypi.org', port=443): Max retries exceeded with url: /simple/pip/ (Caused by SSLError("Can't connect to HTTPS URL because the SSL module is not available.")) - skipping
WARNING: There was an error checking the latest version of pip.

**Comment by L1ghtn1ng** [comment]
What this comes down to is that this is a parrot packaging issue, I would recommend that you move to kali as it will work correctly on that
