### ISSUE TITLE
my theHarvester doesn't work with -b google, how do i fix it?

### ISSUE THREAD

**Issue by AdalbChop759** [laramies/theHarvester#1309]
`theharvester -d kali.org -l 500 -b google`

I get the following output:

 `[!] Invalid source.`

My version is: theHarvester 4.2.0

**Comment by L1ghtn1ng** [comment]
Google is not a source it was removed in 4.2.0 due to Google blocking us. It was mentioned in the release notes

On 21 Jan 2023, at 18:53, AdalbChop759 ***@***.***> wrote:

﻿

theharvester -d kali.org -l 500 -b google

I get the following output:

[!] Invalid source.

My version is: theHarvester 4.2.0
