### ISSUE TITLE
[Other] Failing test tests/discovery/test_sublist3r.py

### ISSUE THREAD

**Issue by elboulangero** [laramies/theHarvester#1345]
In Kali Linux CI, I noticed that `test_sublist3r.py` failed:

```
____________________________ TestSublist3r.test_api ____________________________

self = <tests.discovery.test_sublist3r.TestSublist3r object at 0x7fc91dd5ad90>

    async def test_api(self):
        base_url = f'https://api.sublist3r.com/search.php?domain={TestSublist3r.domain()}'
        headers = {'User-Agent': Core.get_user_agent()}
        request = requests.get(base_url, headers=headers)
>       assert request.status_code == 200
E       assert 522 == 200
E        +  where 522 = <Response [522]>.status_code

tests/discovery/test_sublist3r.py:22: AssertionError
```

Indeed:

```
$ wget -nv -O- https://api.sublist3r.com/
https://api.sublist3r.com/:
2023-03-01 16:08:29 ERROR 522: (no description).

$ wget -nv -O- https://sublist3r.com/
https://sublist3r.com/:
2023-03-01 16:06:52 ERROR 522: (no description).
```

I don't know whether it's temporary

**Comment by L1ghtn1ng** [comment]
Thanks, yeah I think it might of been like this for a while and will need to do some digging on what is going on on as otherwise will remove it

On 1 Mar 2023, at 09:09, Arnaud Rebillout ***@***.***> wrote:

﻿

In Kali Linux CI, I noticed that test_sublist3r.py failed:

____________________________ TestSublist3r.test_api ____________________________

self = <tests.discovery.test_sublist3r.TestSublist3r object at 0x7fc91dd5ad90>

    async def test_api(self):
        base_url = f'https://api.sublist3r.com/search.php?domain={TestSublist3r.domain()}'
        headers = {'User-Agent': Core.get_user_agent()}
        request = requests.get(base_url, headers=headers)
>       assert request.status_code == 200
E       assert 522 == 200
E        +  where 522 = <Response [522]>.status_code

tests/discovery/test_sublist3r.py:22: AssertionError


Indeed:

$ wget -nv -O- https://api.sublist3r.com/
https://api.sublist3r.com/:
2023-03-01 16:08:29 ERROR 522: (no description).

$ wget -nv -O- https://sublist3r.com/
https://sublist3r.com/:
2023-03-01 16:06:52 ERROR 522: (no description).


I don't know whether it's temporary

**Comment by L1ghtn1ng** [comment]
I have removed the test as the site seems to be down permanently
