### ISSUE TITLE
[Bug] Unable to query Threatcrowd due to SSL error

### ISSUE THREAD

**Issue by johnflan** [laramies/theHarvester#1367]
**Screenshots**
`An exception has occurred: Cannot connect to host www.threatcrowd.org:443 ssl:True [SSLCertVerificationError: (1, "[SSL: CERTIFICATE_VERIFY_FAILED] certificate verify failed: Hostname mismatch, certificate is not valid for 'www.threatcrowd.org'. (_ssl.c:992)")]
string indices must be integers, not 'str'
[*] Searching Threatcrowd.`

**System Information (System that tool is running on):**
 - version 4.2 installed via Brew on MacOS

**Additional context**

**Comment by L1ghtn1ng** [comment]
It sounds like you have a proxy that is blocking connections from that cert error for badui and this one because it is man in the middling your connection which would explain the cert issues.

On 27 Mar 2023, at 17:43, John Flanagan ***@***.***> wrote:

﻿

Screenshots
An exception has occurred: Cannot connect to host www.threatcrowd.org:443 ssl:True [SSLCertVerificationError: (1, "[SSL: CERTIFICATE_VERIFY_FAILED] certificate verify failed: Hostname mismatch, certificate is not valid for 'www.threatcrowd.org'. (_ssl.c:992)")] string indices must be integers, not 'str' [*] Searching Threatcrowd.

System Information (System that tool is running on):

  *   OS: [e.g. Windows10]
  *   Version [e.g. 2.7]

Additional context
Add any other context about the problem here.

**Comment by NotoriousRebel** [comment]
@L1ghtn1ng There is no proxy issue the site is just a 503 atm
![image](https://user-images.githubusercontent.com/36310667/228070368-03375b78-01c2-426f-b025-93975c244525.png)

**Comment by L1ghtn1ng** [comment]
closing this out and as part of #1381 it is being removed, but if the site ever comes back can be re-added easliy
