### ISSUE TITLE
First Run Cannot be Completed

### ISSUE THREAD

**Issue by Pseud0nym13** [laramies/theHarvester#1375]
**Feature Request or Bug or Other**
Other

**Describe the feature request or bug or other**
I am cloning the repo and installing all the requirements in my home directory, the first time i try to run it with python3 theHarvester.py I am getting the following error:

'Traceback (most recent call last):
  File "/home/nick/theHarvester/theHarvester.py", line 5, in <module>
    from theHarvester import __main__
  File "/home/nick/theHarvester/theHarvester/__main__.py", line 4, in <module>
    from theHarvester.discovery import dnssearch, takeover, shodansearch
  File "/home/nick/theHarvester/theHarvester/discovery/dnssearch.py", line 17, in <module>
    from theHarvester.lib import hostchecker
  File "/home/nick/theHarvester/theHarvester/lib/hostchecker.py", line 14, in <module>
    class Checker:
  File "/home/nick/theHarvester/theHarvester/lib/hostchecker.py", line 37, in Checker
    BaseException | Any, BaseException | Any, BaseException | Any, BaseException | Any, BaseException | Any]:
TypeError: unsupported operand type(s) for |: 'type' and '_SpecialForm'
'
**To Reproduce**
Steps to reproduce the behaviour:
Clone the repo
python3 theHarvester.py

**Expected behaviour**
Normal start

**Screenshots**
If possible please add screenshots to help explain your problem.

**System Information (System that tool is running on):**
 - OS: Parrot
 - 6.0.0-12parrot1-amd64

**Additional context**

**Comment by L1ghtn1ng** [comment]
What python3 version are you running?

On 29 Mar 2023, at 13:03, Pseud0nym13 ***@***.***> wrote:

﻿

Note we do not support installing theHarvester on andriod

Feature Request or Bug or Other
Other

Describe the feature request or bug or other
I am cloning the repo and installing all the requirements in my home directory, the first time i try to run it with python3 theHarvester.py I am getting the following error:

'Traceback (most recent call last):
File "/home/nick/theHarvester/theHarvester.py", line 5, in
from theHarvester import main
File "/home/nick/theHarvester/theHarvester/main.py", line 4, in
from theHarvester.discovery import dnssearch, takeover, shodansearch
File "/home/nick/theHarvester/theHarvester/discovery/dnssearch.py", line 17, in
from theHarvester.lib import hostchecker
File "/home/nick/theHarvester/theHarvester/lib/hostchecker.py", line 14, in
class Checker:
File "/home/nick/theHarvester/theHarvester/lib/hostchecker.py", line 37, in Checker
BaseException | Any, BaseException | Any, BaseException | Any, BaseException | Any, BaseException | Any]:
TypeError: unsupported operand type(s) for |: 'type' and '_SpecialForm'
'
To Reproduce
Steps to reproduce the behaviour:
Clone the repo
python3 theHarvester.py

Expected behaviour
Normal start

Screenshots
If possible please add screenshots to help explain your problem.

System Information (System that tool is running on):

  *   OS: Parrot
  *   6.0.0-12parrot1-amd64

Additional context
Add any other context about the problem here.

**Comment by L1ghtn1ng** [comment]
You need to use python3.10 which should fix that issue
