### ISSUE TITLE
Search engine

### ISSUE THREAD

**Issue by TamingSariMY** [laramies/theHarvester#1410]
I think in the past I noticed that this tool also provides an option to search for email information from Google and LinkedIn. please return that option because it is very difficult for me to do pentest if I have to use many tools.

**Comment by L1ghtn1ng** [comment]
LinkedIn used Google and Google was blocking us due to captchas so it got removed as it was creating bug reports for things we cannot control. For emails though we do have other modules that pull emails so it’s all good there.
On 4 May 2023, at 23:21, Mohamad Nur Iman ***@***.***> wrote:

﻿

I think in the past I noticed that this tool also provides an option to search for email information from Google and LinkedIn. please return that option because it is very difficult for me to do pentest if I have to use many tools.

**Comment by NotoriousRebel** [comment]
Down the road AWS gateways will be used which should overcome the difficulties of using Google to obtain subdomains and emails, further testing needs to be done but if successful it will be integrated in the future.
