### ISSUE TITLE
I can't find theharvester configuration file on my Kali machine. Can't find /usr/share/theharvester/ on the machine. I just need to find the folder where I can Include api keys and configure theharvester. Please I need help. Anyone please?

### ISSUE THREAD

**Issue by Peter-omereyone** [laramies/theHarvester#1421]
theharvester version 4.2.0 on my kali machine. I tried running every updates but it's up to date. Don't know if anything is wrong. I tried I usually bump into this issue `

[!] Missing API key for binaryedge.

[!] Missing API key for Censys ID and/or Secret.

[!] Missing API key for fullhunt.

[!] Missing API key for Github.

[!] Missing API key for Hunter.

[!] Missing API key for Intelx.

[!] Missing API key for PentestTools.

[!] Missing API key for ProjectDiscovery.

[!] Missing API key for RocketReach.

[!] Missing API key for Securitytrail.

[!] Missing API key for virustotal.

[!] Missing API key for zoomeye.
An exception has occurred: Cannot serialize non-str key None
[*] Searching Anubis.
An exception has occurred: Cannot connect to host dns.bufferover.run:443 ssl:<ssl.SSLContext object at 0x7fb5fdc7fd10> [Name or service not known]
Searching 0 results.

` but can't find the file to configure it. I think theharvester is preinstalled on my kali

**Comment by Peter-omereyone** [comment]
Also On my end I also get invalid source error ie

`theHarvester -d kali.org -l 500 -b google
*******************************************************************
*  _   _                                            _             *
* | |_| |__   ___    /\  /\__ _ _ ____   _____  ___| |_ ___ _ __  *
* | __|  _ \ / _ \  / /_/ / _` | '__\ \ / / _ \/ __| __/ _ \ '__| *
* | |_| | | |  __/ / __  / (_| | |   \ V /  __/\__ \ ||  __/ |    *
*  \__|_| |_|\___| \/ /_/ \__,_|_|    \_/ \___||___/\__\___|_|    *
*                                                                 *
* theHarvester 4.2.0                                              *
* Coded by Christian Martorella                                   *
* Edge-Security Research                                          *
* cmartorella@edge-security.com                                   *
*                                                                 *
*******************************************************************

[!] Invalid source.
`

**Comment by L1ghtn1ng** [comment]
To add api-keys they need adding to theHarvester api keys file in /etc/theHarvester
It is also in the readme and wiki of this repo. Google got removed due to it being blocked all the time by Google. To see the updated source list do theHarvester -h

On 12 May 2023, at 04:36, Peter-omereyone ***@***.***> wrote:

﻿

Also On my end I also get invalid source error ie

`theHarvester -d kali.org -l 500 -b google

________________________________

  *   _ _ _ *
  *   | || |__ ___ /\ /_ _ _ ____ _____ __| | ___ _ __ *
  *   | | _ \ / _ \ / /_/ / _` | '\ \ / / _ / __| / _ \ '| *
  *   | || | | | __/ / __ / (| | | \ V / _/_ \ || __/ | *
  *   _|| ||___| / // _,|| _/ _||/____|| *
  *

                                                            *


  *   theHarvester 4.2.0 *
  *   Coded by Christian Martorella *
  *   Edge-Security Research *
  *   ***@***.******@***.***> *
  *

                                                            *


________________________________

[!] Invalid source.
`
