### ISSUE TITLE
[Bug] result problem

### ISSUE THREAD

**Issue by LittleYell0wMan** [laramies/theHarvester#1441]
Hi there,
command: `ulimit -n 10240 && python3 theHarvester.py -d foo.com -b all -f foo.json -l 9999 -v -n -t`
Subdomain Takeover have detected something
<img width="598" alt="image" src="https://github.com/laramies/theHarvester/assets/46573679/564fabff-42f5-4ec3-a980-feffaaacfc37">
But the json output file have no result about this content.
<img width="286" alt="image" src="https://github.com/laramies/theHarvester/assets/46573679/0745245c-728c-4baa-84c6-9a15b7fdc5e1">
Maybe other funcion like "Virtual hosts" have the same problem.

**Comment by NotoriousRebel** [comment]
The reason it is not the json output is because the logic was [never coded](https://github.com/laramies/theHarvester/blob/master/theHarvester/discovery/takeover.py) which is my bad. I will add this next week, in the meantime if you want to save the results you can do `python3 theHarvester.py -d foo.com -b all -f foo.json -l 9999 -v -n -t | tee -a foo_output.txt` I will update the fingerprints as they are a bit lackluster and make sure it is saved within JSON results.

**Comment by NotoriousRebel** [comment]
As a sidenote in the meantime you may also want to use [nuclei](https://github.com/projectdiscovery/nuclei) with the [subdomain takeover templates](https://github.com/projectdiscovery/nuclei-templates/tree/main/http/takeovers) for potential other takeover opportunities.
