### ISSUE TITLE
Cenesys Issue - Last Version Kali Linux

### ISSUE THREAD

**Issue by NCNeo** [laramies/theHarvester#1500]
After update to last version of Kali Linux the consults get this error 

**cannot import name 'CensysCertificates' from 'censys.search' (/usr/lib/python3/dist-packages/censys/search/__init__.py)
sys:1: RuntimeWarning: coroutine 'start.<locals>.store' was never awaited
RuntimeWarning: Enable tracemalloc to get the object allocation traceback**

in previous versions all work good.

**Comment by L1ghtn1ng** [comment]
This is fixed in git, kali just needs to pull in the new release, will let them know its out and should hopefully get pulled in relatively quickly

On 29 Jul 2023, at 21:32, NCNeo ***@***.***> wrote:

﻿

After update to last version of Kali Linux the consults get this error

cannot import name 'CensysCertificates' from 'censys.search' (/usr/lib/python3/dist-packages/censys/search/init.py)
sys:1: RuntimeWarning: coroutine 'start..store' was never awaited
RuntimeWarning: Enable tracemalloc to get the object allocation traceback

in previous versions all work good.

**Comment by Trailingslashes** [comment]
Seems to be ok with version 4.4.1
