### ISSUE TITLE
[Bug|Feature Request|Other] Theharvestes tool not work

### ISSUE THREAD

**Issue by Prady18** [laramies/theHarvester#1527]
![the Harvest ](https://github.com/laramies/theHarvester/assets/75109984/7c372392-0c47-4807-a62d-0214133e8bc1)
 
I'm use this command ==> theharvester -d 200 -l 200 -b linkedin -s domain  but this cammand not work please help me
@L1ghtn1ng @

**Comment by NotoriousRebel** [comment]
When youn do `-h` read the options carefully, In your case you would want to do `theharvester -d domain.com -l 200 -b linkedin -s`. However, `-s` stands for  shodan and that is getting reworked and for now linkedin got removed due to google captachas; however, there are numerous other tools out there that can crawl linkedin.

**Comment by Prady18** [comment]
@NotoriousRebel Ok I will 😌 try and then MSG u okay
