### ISSUE TITLE
async def google_workaround(visit_url: str) -> bool | str: TypeError: unsupported operand type(s) for |: 'type' and 'type'

### ISSUE THREAD

**Issue by qiuluo-oss** [laramies/theHarvester#1749]
async def google_workaround(visit_url: str) -> bool | str:
TypeError: unsupported operand type(s) for |: 'type' and 'type'

**Comment by EliorFureraj** [comment]
The documentation and main README states python 3.9+ as a requirement.
This error occurs on python 3.9 due to the usage of '|' syntax in place of Union() from typing library in the discovery/constants.py. The new syntax was introduced in [python 3.10.0 alpha 1](https://docs.python.org/3/whatsnew/changelog.html#python-3-10-0-alpha-1). 

Either we bump requirement to 3.10, or we stick to the older syntax.

**Comment by L1ghtn1ng** [comment]
I would say bump it as 3.10 is pretty wide spread at this point imo

On 16 Jun 2024, at 19:13, Elior Fureraj ***@***.***> wrote:

﻿

The documentation and main README states python 3.9+ as a requirement.
This error occurs on python 3.9 due to the usage of '|' syntax in place of Union() from typing library in the discovery/constants.py. The new syntax was introduced in python 3.10.0 alpha 1<https://docs.python.org/3/whatsnew/changelog.html#python-3-10-0-alpha-1>.

Either we bump requirement to 3.10, or we stick to the older syntax.

**Comment by EliorFureraj** [comment]
I wasn't expecting the quick response, already made a 'fix' pr by reverting type hinting. 
I fully agree, I'll change the PR and just bump the version.
