### ISSUE TITLE
Create unit tests for all modules with pytest

### ISSUE THREAD

**Issue by L1ghtn1ng** [laramies/theHarvester#280]
Title says it all

**Comment by BMFI** [comment]
Traceback (most recent call last):
  File "/usr/bin/theharvester", line 19, in <module>
    from lib import htmlExport
ImportError: cannot import name htmlExport

I am new here, but working on all the jargon, rules and compliance. I am not sure why? I have python3.7 and tried using the gnome or Gui to open and got this Traceback. I downloaded the zip put it on the Desktop, extracted here, next opened theHarvester, lib, and core.py so I copied all the code and loaded it in the terminal. I still get a different traceback either start in the terminal 
root@kali:~/Desktop/theHarvester-master# python3 theHarvester.py
Traceback (most recent call last):
  File "theHarvester.py", line 10, in <module>
    from theHarvester import __main__
  File "/root/Desktop/theHarvester-master/theHarvester/__init__.py", line 1, in <module>
And from the gnome or gui I get
Information gathering, OSINT analysis, TheHarvester gives:
Traceback (most recent call last):
  File "/usr/bin/theharvester", line 19, in <module>
    from lib import htmlExport
ImportError: cannot import name htmlExport
I can be working on this one, but I am slow due to time constraints and figuring out the jargon, rules and compliance, but in the mean time I am real good with quick fixes and shotgun answers, so if anyone has a resolution? I can use the help.

**Comment by L1ghtn1ng** [comment]
You need to make sure you are using the one from git and that you setup a virtualenv and with the virtualenv active run the command to install the required librarys
________________________________

**Comment by BMFI** [comment]
Thank you for the e-mail and quick shotgun answers. I now have theHarvester up and running easy as pie. Thank you

**Comment by BMFI** [comment]
Thank you
