### ISSUE TITLE
[Bug] Docker install: ModuleNotFoundError: No module named 'aiodns'

### ISSUE THREAD

**Issue by fakepop** [laramies/theHarvester#600]
Hello. First time user, installed per the Docker instructions, I am getting:

```$ ./theHarvester.py -d somedomain.com
Traceback (most recent call last):
  File "./theHarvester.py", line 7, in <module>
    from theHarvester import __main__
  File "/.../theHarvester/theHarvester/__main__.py", line 4, in <module>
    from theHarvester.discovery import dnssearch, takeover, shodansearch
  File "/.../theHarvester/theHarvester/discovery/dnssearch.py", line 14, in <module>
    from aiodns import DNSResolver
ModuleNotFoundError: No module named 'aiodns'```

Thanks!

**Comment by NotoriousRebel** [comment]
Are you using the latest version of the tool? Is aiodns within your requirements\base.txt?

**Comment by mjvanhasselt** [comment]
Hello,

Because I got Traceback errors (other tracebacks than the ones discussed in this post) on my just installed Kali machine, I tried to install theharvester on an Ubuntu 18.04 laptop and then I am getting the same Traceback as @fakepop (see screenshot). To install theharvester, I cloned this repository and followed the Docker installation instructions to install last Tuesday on.

@NotoriousRebel, answering your question about `aiodns`: I just checked the file `requirements/base.txt` and the first line is `aiodns==2.0.0`.

Thanks!
![screenshot](https://user-images.githubusercontent.com/30866460/102480333-6a562280-4060-11eb-9131-3762072abc15.png)

**Comment by L1ghtn1ng** [comment]
I have pushed an update that has been pulled into Kali which will fix the issue in Kali with python 3.9 so that should work soon, just keep an eye out for that update
________________________________

**Comment by mjvanhasselt** [comment]
Okay thanks! @L1ghtn1ng

**Comment by mjvanhasselt** [comment]
With respect to this issue: I made a mistake. I should have used `docker run theharvester -h` to start theharvester. So, it does work in Ubuntu.

**Comment by L1ghtn1ng** [comment]
Closing this out

**Comment by tavoweb** [comment]
Same error on ubuntu ...

**Comment by L1ghtn1ng** [comment]
> Same error on ubuntu ...

Sudo apt install python3-aiodns should fix that
