### ISSUE TITLE
Issue Running Shodan Query

### ISSUE THREAD

**Issue by notsure1138** [laramies/theHarvester#601]
I've entered my shodan api key in /etc/api-keys.yaml, but all shodan queries return the same empty results.

theHarvester -d elearnsecurity.com --shodan -l 100
I've tried probably a dozen different domains, all with the same results.

Results-
![image](https://user-images.githubusercontent.com/58577899/100521330-9f114100-3168-11eb-9310-e2b3bf3feda6.png)

Api key is in this syntax-
![image](https://user-images.githubusercontent.com/58577899/100521366-e0a1ec00-3168-11eb-97d1-5224216e85db.png)

I've also tried adding quotes around the key, but no change

I ran Wireshark while running a few queries, and when trying a shodan search, there were 0 packets generated.  Using a different source generates a lot of captured traffic.

I've tried playing around with the command, -s gives the same results, -b shodan gives the expected invalid source error.  

I get the same empty result set with no traffic generated if I remove the api key entirely with no traffic captured in Wireshark.  I would expect to see the "Missing API key" message from the MissingKey class, but that doesn't happen.

Am I using the shodan option incorrectly?

**Comment by NotoriousRebel** [comment]
When you are using the shodan flag you need to also be using the -b flag as well for example `theHarvester -d mywebsite.com -l 100 -s -b google,bing,duckduckgo`. This is because the tool actually needs ips to feed to shodan so when you run it without -b there are no ips to feed to shodan as it hasn't found anything.

**Comment by notsure1138** [comment]
Thank you so much!  Can't believe I didn't think to try that.  It's working now.  I appreciate your help.

**Comment by brandonaaskov** [comment]
@NotoriousRebel, am I missing something still? 
![image](https://user-images.githubusercontent.com/445778/124670025-64e7ea80-de81-11eb-9cc4-9b3864c9447d.png)

And Shodan isn't even listed in the help text, but there is an entry for its key in the yaml file so... I think I'm confused?

![image](https://user-images.githubusercontent.com/445778/124670199-a11b4b00-de81-11eb-9f64-f803edc48273.png)

**Comment by NotoriousRebel** [comment]
@brandonaaskov The reason why Shodan is not included within the list of sources is because Shodan is not a module. You would use Shodan to further query ip addresses that were found.
For example: `python3 theHarvester.py -d netflix.com -l 100 -b duckduckgo,bing,baidu -s` Using `-s` or `--shodan`  indicates that for ip addresses found from modules will be queried within Shodan.

I would also suggest if possible using the latest version of the tool which you would have to install at the moment manually or using docker but if you follow the [wiki instructions](https://github.com/laramies/theHarvester/wiki/Installation) should be trivial. The reason why is because more information is extracted from Shodan and the ability to have JSON output may make it easier for you to further analyze results.

**Comment by brandonaaskov** [comment]
@NotoriousRebel thank you very much for that, I clearly should have read _all_ the flags before "getting lost." 😬
