### ISSUE TITLE
[Bug] Docker build failed

### ISSUE THREAD

**Issue by whoo** [laramies/theHarvester#705]
Bug | Docker build failed due to lxml-4.6.3 unavailable in **python:alpine3.13**

**Describe the feature request or bug or other**
Fail to build container

**To Reproduce**
Steps to reproduce the behaviour:
https://github.com/laramies/theHarvester/wiki/Installation#option-2---docker

```
#12 17.49 ERROR: Could not find a version that satisfies the requirement lxml==4.6.3
#12 17.50 ERROR: No matching distribution found for lxml==4.6.3
------
executor failed running [/bin/sh -c pip3 install --no-cache-dir -r requirements.txt]: exit code: 1
```

For now , i suggest to update:
```diff
-lxml==4.6.3
+lxml==4.6.2
```

**Comment by L1ghtn1ng** [comment]
Unfortunately it needs to be that due to that version fixing a security issue
________________________________
From: Dominique DERRIER ***@***.***>
Sent: Monday, March 22, 2021 1:08:39 PM
To: laramies/theHarvester ***@***.***>
Cc: Subscribed ***@***.***>
Subject: [laramies/theHarvester] [Bug] Docker build failed (#705)


Bug | Docker build failed due to lxml-4.6.3 unavailable in python:alpine3.13

Describe the feature request or bug or other
Fail to build container

To Reproduce
Steps to reproduce the behaviour:
https://github.com/laramies/theHarvester/wiki/Installation#option-2---docker

#12 17.49 ERROR: Could not find a version that satisfies the requirement lxml==4.6.3
#12 17.50 ERROR: No matching distribution found for lxml==4.6.3
------
executor failed running [/bin/sh -c pip3 install --no-cache-dir -r requirements.txt]: exit code: 1


For now , i suggest to update:

-lxml==4.6.3
+lxml==4.6.2

**Comment by L1ghtn1ng** [comment]
@whoo Can you please tell me if it is working now?
