### ISSUE TITLE
RequestsDependencyWarning: urllib3 (1.21.1) or chardet (2.1.1) doesn't match a supported version!

### ISSUE THREAD

**Issue by darkmatter1505** [laramies/theHarvester#75]
Trying to run theharvester on kali 2017.3 rolling but I get this error message.

/usr/lib/python2.7/dist-packages/requests/__init__.py:80: RequestsDependencyWarning: urllib3 (1.21.1) or chardet (2.1.1) doesn't match a supported version!
  RequestsDependencyWarning)
Request library not found, please install it before proceeding

I have checked and my urllib3 is the correct version and my chardet is correct as well.

**Comment by jzold** [comment]
hi darkmatter1505

This ticket is without any updates for a long time :) In fact ever since quite a few kali versions have been released. The version you were using at the time might had dependency issues (sometimes it may happen) which now has been fixed.

As of today the latest is Kali 2018.3. I had a quick look and by default it comes with theHarvester v2.7.2. I tested and harvester works perfectly without any dependency issues. I assume you have upgraded your kali version since you raised this issue which means this issue is now resolved.

Thanks
J./

**Comment by njfox** [comment]
I just got this error today on a fresh kali image. I installed `theharvester` from the official repositories and got the following error when I tried to run it:
```
root@kali:~# theharvester
/usr/local/lib/python2.7/dist-packages/requests/__init__.py:80: RequestsDependencyWarning: urllib3 (1.24) or chardet (3.0.4) doesn't match a supported version!
  RequestsDependencyWarning)
Request library not found, please install it before proceeding
```
`python-urllib3` and `python-chardet` are installed and are the correct versions based on the output.
