### ISSUE TITLE
[Bug] File Not Found /etc/theHarvester/proxies.yaml

### ISSUE THREAD

**Issue by oxr463** [laramies/theHarvester#776]
**Feature Request or Bug or Other**
Bug

**Describe the feature request or bug or other**

Running `theHarvester` from my terminal complains about this missing `proxies.yaml` file.

**To Reproduce**
Steps to reproduce the behaviour:
1. Install via the following commands:

```
git clone https://github.com/laramies/theharvester /opt/theharvester
cd /opt/theharvester && \
  python3 -m pip install -r requirements/base.txt && \
  ln -sf /opt/theharvester/theHarvester.py /usr/local/bin/theHarvester
```
Source: https://github.com/oxr463/pentesting-vm/blob/master/Vagrantfile#L69

2. Run `theHarvester` without any arguments.
3. See the error.

**Expected behaviour**
I was expecting help text, not a crash.

**Screenshots**
If possible please add screenshots to help explain your problem.

N/A

**System Information (System that tool is running on):**
 - OS: Alpine Linux 3.13
 - Version: https://github.com/laramies/theHarvester/tree/master

**Additional context**

I tried to fake the file using these commands:

```
sudo su
mkdir /etc/theHarvester
touch /etc/theHarvester/proxies.yaml
exit
```

But it still fails:

```
theHarvester
Traceback (most recent call last):
  File "/usr/local/bin/theHarvester", line 7, in <module>
    from theHarvester import __main__
  File "/opt/theharvester/theHarvester/__main__.py", line 4, in <module>
    from theHarvester.discovery import dnssearch, takeover, shodansearch
  File "/opt/theharvester/theHarvester/discovery/takeover.py", line 1, in <module>
    from theHarvester.lib.core import *
  File "/opt/theharvester/theHarvester/lib/core.py", line 377, in <module>
    class AsyncFetcher:
  File "/opt/theharvester/theHarvester/lib/core.py", line 378, in AsyncFetcher
    proxy_list = Core.proxy_list()
  File "/opt/theharvester/theHarvester/lib/core.py", line 83, in proxy_list
    http_list = [f'http://{proxy}' for proxy in keys['http']] if keys['http'] is not None else []
TypeError: 'NoneType' object is not subscriptable
```

**Comment by L1ghtn1ng** [comment]
The easiest way to install this is 2 options. Use the docker image which uses alpine or create a virtual environment and run it from the directory.
________________________________
From: Lucas Ramage ***@***.***>
Sent: Tuesday, June 22, 2021 7:23:27 PM
To: laramies/theHarvester ***@***.***>
Cc: Subscribed ***@***.***>
Subject: [laramies/theHarvester] [Bug] File Not Found /etc/theHarvester/proxies.yaml (#776)


Feature Request or Bug or Other
Bug

Describe the feature request or bug or other

Running theHarvester from my terminal complains about this missing proxies.yaml file.

To Reproduce
Steps to reproduce the behaviour:

  1.  Install via the following commands:

git clone https://github.com/laramies/theharvester /opt/theharvester
cd /opt/theharvester && \
  python3 -m pip install -r requirements/base.txt && \
  ln -sf /opt/theharvester/theHarvester.py /usr/local/bin/theHarvester


  1.  Run theHarvester without any arguments.
  2.  See the error.

Expected behaviour
I was expecting help text, not a crash.

Screenshots
If possible please add screenshots to help explain your problem.

N/A

System Information (System that tool is running on):

  *   OS: Alpine Linux 3.13
  *   Version: https://github.com/laramies/theHarvester/tree/master

Additional context

I tried to fake the file using these commands:

sudo su
mkdir /etc/theHarvester
touch /etc/theHarvester/proxies.yaml
exit


But it still fails:

theHarvester
Traceback (most recent call last):
  File "/usr/local/bin/theHarvester", line 7, in <module>
    from theHarvester import __main__
  File "/opt/theharvester/theHarvester/__main__.py", line 4, in <module>
    from theHarvester.discovery import dnssearch, takeover, shodansearch
  File "/opt/theharvester/theHarvester/discovery/takeover.py", line 1, in <module>
    from theHarvester.lib.core import *
  File "/opt/theharvester/theHarvester/lib/core.py", line 377, in <module>
    class AsyncFetcher:
  File "/opt/theharvester/theHarvester/lib/core.py", line 378, in AsyncFetcher
    proxy_list = Core.proxy_list()
  File "/opt/theharvester/theHarvester/lib/core.py", line 83, in proxy_list
    http_list = [f'http://{proxy}' for proxy in keys['http']] if keys['http'] is not None else []
TypeError: 'NoneType' object is not subscriptable

**Comment by oxr463** [comment]
Workaround: `cp /opt/theHarvester/proxies.yaml /etc/theHarvester`

**Comment by adityatelange** [comment]
@oxr463 I use the following:

```
git clone https://github.com/laramies/theHarvester --depth=1
cd theHarvester
sudo pip3 install -r requirements/base.txt
sudo python3 setup.py install
```

That way we could use `theHarvester` from anywhere + no errors

**Comment by L1ghtn1ng** [comment]
Please check the readme on the install section but you can also do what Aditya has said. These are the supported install methods
________________________________
