### ISSUE TITLE
[Feature Request] Alias `harvest` for `theHarvester` command

### ISSUE THREAD

**Issue by oxr463** [laramies/theHarvester#777]
**Feature Request or Bug or Other**
Feature Request

**Describe the feature request or bug or other**

Typing `theHarvester` is kind of awkward. Especially the capital letter in the middle.

**To Reproduce**
Steps to reproduce the behaviour: N/A

**Expected behaviour**

It would be cool if there was an official alias, e.g., `harvest`

**Screenshots**
If possible please add screenshots to help explain your problem.

N/A

**System Information (System that tool is running on):**
 - OS: Any
 - Version: All

**Additional context**

N/A

**Comment by L1ghtn1ng** [comment]
You should be able to do tab complete on it?
________________________________
From: Lucas Ramage ***@***.***>
Sent: Tuesday, June 22, 2021 7:27:11 PM
To: laramies/theHarvester ***@***.***>
Cc: Subscribed ***@***.***>
Subject: [laramies/theHarvester] [Feature Request] Alias `harvest` for `theHarvester` command (#777)


Feature Request or Bug or Other
Feature Request

Describe the feature request or bug or other

Typing theHarvester is kind of awkward. Especially the capital letter in the middle.

To Reproduce
Steps to reproduce the behaviour: N/A

Expected behaviour

It would be cool if there was an official alias, e.g., harvest

Screenshots
If possible please add screenshots to help explain your problem.

N/A

System Information (System that tool is running on):

  *   OS: Any
  *   Version: All

Additional context
Add any other context about the problem here.

N/A

**Comment by oxr463** [comment]
Workaround:

```
ln -sf /usr/local/bin/theHarvester /usr/local/bin/theharvester && \
ln -sf /usr/local/bin/theHarvester /usr/local/bin/harvest
```

**Comment by NotoriousRebel** [comment]
@oxr463 Please also see this [post[(https://askubuntu.com/questions/17536/how-do-i-create-a-permanent-bash-alias) as an alternative to creating a symbolic link this just uses an alias and adds it to your bashrc.

**Comment by L1ghtn1ng** [comment]
Thanks Matt
