### ISSUE TITLE
[Bug] v4 contantly crashing

### ISSUE THREAD

**Issue by six2dez** [laramies/theHarvester#852]
**Feature Request or Bug or Other**
v4 contantly crashing

**Describe the feature request or bug or other**
Since v4, every source is returning error `'NoneType' object has no attribute 'get'` even from fresh installation.

**To Reproduce**
Install the tool following the wiki and run `python3 theHarvester.py -d domain.com -b all`

**Expected behaviour**
Results appearing

**Screenshots**
![image](https://user-images.githubusercontent.com/24670991/133063976-486e68e1-c2c9-4bbf-8127-bb94865ca404.png)
![image](https://user-images.githubusercontent.com/24670991/133064049-00a35b33-28b8-46c4-ae22-f4937e0e75f0.png)

**System Information (System that tool is running on):**
 - OS: Kali Rolling latest and Ubuntu 20.04

**Comment by L1ghtn1ng** [comment]
Can you please make sure that you are using a python virtual environment as I cannot reproduce this, I can omnisint as that is returning a 525 host error as it seems there is a issue with that domain at the moment

**Comment by NotoriousRebel** [comment]
@six2dez Thank you for creating this issue, I have noticed at least with Windows that with `-b all` it has caused issues due to too [many file descriptors](https://stackoverflow.com/questions/47675410/python-asyncio-aiohttp-valueerror-too-many-file-descriptors-in-select-on-win). I wrote the asyncio portion of the code years ago when I was still new to asyncio and didn't thoroughly understand it. Plans to rework the asyncio queue and perhaps use something like [aiojobs](https://github.com/aio-libs/aiojobs). As something like celery or airflow are not unnecessary and only adds to complexity. Also seems like omnisint. works just fine; although, they changed how data is returned so that will need to be updated. In the meantime, if you are still getting this issue please try changing [this line](https://github.com/laramies/theHarvester/blob/master/theHarvester/discovery/omnisint.py) from 3 to 1.  Also thank you for the awesome scripts, very handy :)

**Comment by six2dez** [comment]
> @six2dez Thank you for creating this issue, I have noticed at least with Windows that with `-b all` it has caused issues due to too [many file descriptors](https://stackoverflow.com/questions/47675410/python-asyncio-aiohttp-valueerror-too-many-file-descriptors-in-select-on-win). I wrote the asyncio portion of the code years ago when I was still new to asyncio and didn't thoroughly understand it. Plans to rework the asyncio queue and perhaps use something like [aiojobs](https://github.com/aio-libs/aiojobs) or [apscheduler](https://github.com/agronholm/apscheduler). As something like celery or airflow are not unnecessary and only adds to complexity. Also seems like omnisint. works just fine; although, they changed how data is returned so that will need to be updated. In the meantime, if you are still getting this issue please try changing [this line](https://github.com/laramies/theHarvester/blob/master/theHarvester/discovery/omnisint.py) from 3 to 1. Also thank you for the awesome scripts, very handy :)

Hey! @NotoriousRebel thanks for your explanation, I've updated the tool right now and those errors are not happening anymore, now it's failing only Spyse source. Running it with all sources except Spyse doesn't produce any error :) Also thanks for your words and for your work on theHarvester, it's an essential tool.

**Comment by L1ghtn1ng** [comment]
@six2dez You happy for this to be closed?

**Comment by six2dez** [comment]
Yes! Thank you!
