### ISSUE TITLE
[Bug] Not all results are showed

### ISSUE THREAD

**Issue by javisomoza** [laramies/theHarvester#945]
theHarvester output shows for example "Hosts found: 117" but only less than 40 results are showed.

**To Reproduce**
Steps to reproduce the behaviour:
1. Run tool like this: python3 theHarvester.py -b all -d marca.es   (it happens with any other domain with multiple results)
2. See output

**Expected behaviour**
All the results to be showed

**Screenshots**
![image](https://user-images.githubusercontent.com/49761255/145622389-6eb60e26-77d3-4de3-a61b-897f239bd5c2.png)

**System Information (System that tool is running on):**
 - OS: Linux kali 5.14.0-kali4-amd64
 - theHarvester: 4.0.3 (tried the Kali version and "from source" installed version)
 - python 3.9.9
 - pip 20.3.4

**Comment by NotoriousRebel** [comment]
@javisomoza If you are still curious about the reason for this see this line where it [prints number of hosts found](https://github.com/laramies/theHarvester/blob/master/theHarvester/__main__.py#L637). Two lines after is where it gets deduped, so the reason for this is most likely due to duplicates.
