### ISSUE TITLE
[Bug|Feature Request|Other] Short Description of Issue

### ISSUE THREAD

**Issue by rdgeno12** [laramies/theHarvester#949]
## Note we do not support installing theHarvester on andriod

**Feature Request or Bug or Other**
I hope this is what goes here.
[Error saving JSON file] [!] An error occurred while saving the JSON file: a bytes-like object is required, not 'str'

**Describe the feature request or bug or other**
[Error saving JSON file] [!] An error occurred while saving the JSON file: a bytes-like object is required, not 'str'

**To Reproduce**
Steps to reproduce the behaviour:
1. Run theHarvester normally.
2. See error : [Error saving JSON file] [!] An error occurred while saving the JSON file: a bytes-like object is required, not 'str'

**Expected behaviour**
I expected it to run without [Error saving JSON file] [!] An error occurred while saving the JSON file: a bytes-like object is required, not 'str'

**Screenshots**
If possible please add screenshots to help explain your problem.

**System Information (System that tool is running on):**
 Kali Linux the newest version.

**Additional context**
I'm running theHarvester on the current version of Kali Linux. I found my issue but it says it was fixed with the current version of theHarvester that was 17 days ago and I'm running the current version. I looked for a solution but there's no solution that I can find. This is the what I'm getting.
[Error saving JSON file] [!] An error occurred while saving the JSON file: a bytes-like object is required, not 'str'
I even went as far as removing theHarvester and reinstalling it.
Sorry if I filled this out strange I haven't filled one out in a long time.

**Comment by NotoriousRebel** [comment]
Please do a git pull as there was an error that caused that error that was fixed.

**Comment by rdgeno12** [comment]
Worked perfectly thank you.

**Comment by rdgeno12** [comment]
It worked for about 30 minutes it started saying the same thing. I deleted theHarvester and reinstalled exactly like I did before and it's saying the same thing.

**Comment by rdgeno12** [comment]
If you have an answer for this I can close this.
When I run theHarvester without running it trough Tor I don't get the Json error it's only when I run everything through Tor.
Is theHarvester incompatible with Tor?

**Comment by L1ghtn1ng** [comment]
@rdgeno12 can you give repo steps please?

**Comment by L1ghtn1ng** [comment]
@rdgeno12 you still having this issue, as mentioned can you also give reproduce steps please

**Comment by pablosnt** [comment]
Hi @L1ghtn1ng @NotoriousRebel

I have the same problem using theHarvester (version 4.0.3) for Kali Linux (release 2022.1). To reproduce it, you can use the command `theHarvester -d <domain> -f somefile.json`.

**However, as you said, this bug seems fixed when I use theHarvester from source.**

Sorry for the question, but I usually use the default theHarvester installation for Kali Linux, so I would like to know if do you have some ETA to release the next version with the fix to this issue. So that, I will be able to use theHarvester as I usually did.

Thank you for your time and congratulations for this amazing tool!

**Comment by L1ghtn1ng** [comment]
Thank you for the kind words. Am going to be having a look at everything and fixing any issues I find etc over the uk Easter break so am hoping to get one out soon after that. Keep an eye on my twitter as I post there when I tag a new release.

Thanks,
Jay

On 12 Apr 2022, at 12:32, Pablo Santiago ***@***.***> wrote:

﻿

Hi @L1ghtn1ng<https://github.com/L1ghtn1ng> @NotoriousRebel<https://github.com/NotoriousRebel>

I have the same problem using theHarvester (version 4.0.3) for Kali Linux (release 2022.1). To reproduce it, you can use the command theHarvester -d <domain> -f somefile.json.

However, as you said, this bug seems fixed when I use theHarvester from source.

Sorry for the question, but I usually use the default theHarvester installation for Kali Linux, so I would like to know if do you have some ETA to release the next version with the fix to this issue. So that, I will be able to use theHarvester as I usually did.

Thank you for your time and congratulations for this amazing tool!

**Comment by L1ghtn1ng** [comment]
This was resolved a while ago
